// Plantillas oficiales World Cup 2026
// Fuente: GiveMeSport / FIFA (confirmadas al 2 de junio 2026)

export const SQUADS = {
  // GRUPO A
  "Chequia": ["Matej Kovar","Jindrich Stanek","Lukas Hornicek","Vladimir Coufal","Tomas Holes","Ladislav Krejcki","David Zima","Jaroslav Zeleny","David Jurasek","David Doudera","Robin Hranec","Stepan Chaloupek","Tomas Soucek","Vladimir Darida","Lukas Provod","Michal Sadilek","Pavel Sulc","Hugo Sochurek","Alexandr Sojka","Denis Visinsky","Patrik Schick","Adam Hlozek","Jan Kuchta","Mojmir Chytil","Tomas Chory","Lukas Serv"],
  "México": ["Guillermo Ochoa","Raul Rangel","Carlos Acevedo","Jesus Gallardo","Cesar Montes","Jorge Sanchez","Johan Vasquez","Israel Reyes","Mateo Chavez","Edson Alvarez","Orbelin Pineda","Luis Romo","Roberto Alvarado","Luis Chavez","Eric Lira","Gilberto Mora","Brian Gutierrez","Obed Vargas","Alvaro Fidalgo","Raul Jimenez","Alexis Vega","Santiago Gimenez","Cesar Huerta","Julian Quinones","Guillermo Martinez","Armando Gonzalez"],
  "Sudáfrica": ["Ronwen Williams","Ricardo Goss","Sipho Chaine","Aubrey Modiba","Khuliso Mudau","Nkosinathi Sibisi","Mbekezeli Mbokazi","Ime Okon","Samukele Kabini","Khulumani Ndamane","Thabang Matuludi","Kamogelo Sebelebele","Bradley Cross","Olwethu Makhanya","Teboho Mokoena","Sphephelo Sithole","Thalente Mbatha","Jayden Adams","Themba Zwane","Lyle Foster","Evidence Makgopa","Oswin Appollis","Iqraam Rayners","Relebohile Mofokeng","Thapelo Maseko","Tshepang Moremi"],
  "Corea del Sur": ["Kim Seung-Gyu","Jo Hyeon-woo","Song Bum-keun","Kim Min-jae","Kim Moon-hwan","Seol Young-woo","Cho Yu-min","Lee Tae-seok","Park Jin-seob","Kim Tae-hyeon","Lee Han-beom","Jens Castrop","Lee Ki-hyuk","Lee Jae-sung","Hwang Hee-chan","Hwang In-beom","Lee Kang-in","Paik Seung-ho","Kim Jin-gyu","Lee Dong-gyeong","Bae Jun-ho","Eom Ji-Sung","Yang Hyun-jun","Son Heung-min","Cho Gue-sung","Oh Hyeon-gyu"],
  // GRUPO B
  "Bosnia y Herz.": ["Nikola Vasilj","Martin Zlomislic","Osman Hadzikic","Sead Kolasinac","Dennis Hadzikadunic","Amar Dedic","Nikola Katic","Tarik Muharemovic","Nihad Mujakic","Stjepan Radeljic","Nidal Celik","Amir Hadziahmetovic","Benjamin Tahirovic","Armin Gigovic","Dzenis Burnic","Ivan Basic","Esmir Bajraktarevic","Amar Memic","Ivan Sunjic","Kerim Alajbegovic","Ermin Mahmic","Edin Dzeko","Ermedin Demirovic","Samed Bazdar","Haris Tabakovic","Jovo Lukic"],
  "Canadá": ["Dayne St Clair","Maxime Crepeau","Owen Goodman","Alistair Johnston","Luc de Fougerolles","Alfie Jones","Joel Waterman","Derek Cornelius","Moise Bombito","Alphonso Davies","Richie Laryea","Niko Sigur","Mathieu Choiniere","Stephen Eustaquio","Ismael Kone","Liam Millar","Jacob Schaffelburg","Tajon Buchanan","Ali Ahmed","Jonathan Osorio","Nathan Saliba","Cyle Larin","Jonathan David","Tani Oluwaseyi","Promise David","Marcelo Flores"],
  "Qatar": ["Meshaal Barsham","Yousef Hassan","Bassel Salman","Pedro Miguel","Ismaeel Mohammad","Boualem Khoukhi","Musab Khoder","Abdelkarim Hassan","Karim Boudiaf","Assim Madibo","Jassem Gaber","Hassan Al-Haydos","Akram Afif","Mohammed Muntari","Almoez Ali","Yousuf Abdurisag","Abdullah Al-Ahrak","Homam Ahmed","Ahmed Alaaeldin","Khaled Ibrahim","Ahmad Moein","Ismail Mohamad","Bassam Al-Rawi","Khalid Muneer","Ahmed Fadel","Omar Khaled"],
  "Suiza": ["Marvin Keller","Gregor Kobel","Yvon Mvogo","Manuel Akanji","Aurele Amenda","Eray Comert","Nico Elvedi","Luca Jaquez","Miro Muheim","Ricardo Rodriguez","Silvan Widmer","Michel Aebischer","Christian Fassnacht","Remo Freuler","Ardon Jashari","Johan Manzambi","Fabian Rieder","Djibril Sow","Ruben Vargas","Granit Xhaka","Denis Zakaria","Zeki Amdouni","Breel Embolo","Cedric Itten","Dan Ndoye","Noah Okafor"],
  // GRUPO C
  "Brasil": ["Alisson","Ederson","Weverton","Marquinhos","Danilo Luiz","Alex Sandro","Gabriel Magalhaes","Bremer","Wesley","Roger Ibanez","Douglas Santos","Leo Pereira","Casemiro","Lucas Paqueta","Bruno Guimaraes","Fabinho","Danilo Santos","Neymar","Vinicius Jr","Raphinha","Gabriel Martinelli","Matheus Cunha","Endrick","Luiz Henrique","Igor Thiago","Rayan"],
  "Haití": ["Johny Placide","Alexandre Pierre","Josue Duverger","Ricardo Ade","Carlens Arcus","Martin Experience","Jean-Kevin Duverne","Duke Lacroix","Wilguens Paugain","Hannes Delcroix","Keeto Thermoncy","Leverton Pierre","Danley Jean Jacques","Carl Sainte","Jean-Ricner Bellegarde","Woodensky Pierre","Dominique Simon","Duckens Nazon","Frantzdy Pierrot","Derrick Etienne Jr","Louicius Deedson","Ruben Providence","Josue Casimir","Yassin Fortune","Wilson Isidor","Lenny Joseph"],
  "Marruecos": ["Yassine Bounou","Munir Mohamedi","Ahmed Reda Tagnaouti","Achraf Hakimi","Nayef Aguerd","Noussair Mazraoui","Youssef Belammari","Anass Salah-Eddine","Chadi Riad","Issa Diop","Zakaria El Ouahdi","Redouane Halhal","Sofyan Amrabat","Azzedine Ounahi","Bilal El Khannouss","Ismael Saibari","Neil El Aynaoui","Samir El Mourabet","Ayyoub Bouaddi","Ayoub El Kaabi","Soufiane Rahimi","Brahim Diaz","Abde Ezzalzouli","Chemsdine Talbi","Gessime Yassine","Ayoube Amaimouni"],
  "Escocia": ["Angus Gunn","Craig Gordon","Liam Kelly","Andy Robertson","Kieran Tierney","Anthony Ralston","John Souttar","Scott McKenna","Jack Hendry","Aaron Hickey","Nathan Patterson","Grant Hanley","Dominic Hyam","Scott McTominay","Tyler Fletcher","John McGinn","Kenny McLean","Lewis Ferguson","Ryan Christie","Findlay Curtis","Ben Gannon-Doak","Lawrence Shankland","George Hirst","Che Adams","Ross Stewart","Lyndon Dykes"],
  // GRUPO D
  "Australia": ["Mathew Ryan","Paul Izzo","Patrick Beach","Aziz Behich","Milos Degenek","Harry Souttar","Jordan Bos","Cameron Burgess","Jason Geria","Alessandro Circati","Kai Trewin","Jacob Italiano","Lucas Herrington","Jackson Irvine","Ajdin Hrustic","Connor Metcalfe","Aiden O'Neill","Paul Okon-Engstler","Cammy Devlin","Mathew Leckie","Awer Mabil","Nestory Irankunda","Mohamed Toure","Nishan Velupillay","Cristian Volpato","Tete Yengi"],
  "Paraguay": ["Antony Silva","Rodrigo Munoz","Xavier Coronel","Junior Alonso","Gustavo Gomez","Fabian Balbuena","Santiago Arzamendia","Omar Alderete","Robert Rojas","Alonso Cubas","Richard Sanchez","Miguel Almiron","Matias Espinoza","Rodrigo Rojas","Andres Cubas","Kaku","Gabriel Avalos","Braian Samudio","Diego Leon","Carlos Gonzalez","Ivan Angulo","Fernando Cardozo","Julio Enciso","Antonio Sanabria","Jorge Morel","Roberto Fernandez"],
  "Turquía": ["Mert Gunok","Ugurcan Cakir","Altay Bayindir","Mert Muldur","Zeki Celik","Kaan Ayhan","Samet Akaydin","Ferdi Kadioglu","Cenk Tosun","Hakan Calhanoglu","Arda Guler","Kenan Yildiz","Orkun Kokcu","Salih Ozcan","Okay Yokuslu","Yusuf Yazici","Ismail Yuksek","Bertuğ Yildirim","Muhammed Sengoz","Baris Alper Yilmaz","Cengiz Under","Efecan Karaca","Halil Dervisoglu","Umut Bozok","Serdar Dursun","Yunus Akgun"],
  "USA": ["Matt Turner","Chris Brady","Matt Freese","Sergino Dest","Chris Richards","Antonee Robinson","Auston Trusty","Miles Robinson","Tim Ream","Alex Freeman","Mark McKenzie","Joe Scally","Tyler Adams","Weston McKennie","Christian Pulisic","Sebastian Berhalter","Cristian Roldan","Malik Tillman","Gio Reyna","Ricardo Pepi","Brenden Aaronson","Max Arfsten","Haji Wright","Folarin Balogun","Tim Weah","Alex Zendejas"],
  // GRUPO E
  "Alemania": ["Manuel Neuer","Oliver Baumann","Alexander Nubel","Antonio Rudiger","Jonathan Tah","Nico Schlotterbeck","Nathaniel Brown","David Raum","Malick Thiaw","Waldemar Anton","Pascal Gross","Joshua Kimmich","Leon Goretzka","Lennart Karl","Jamal Musiala","Florian Wirtz","Jamie Leweling","Aleksandar Pavlovic","Maximilian Beier","Nadiem Amiri","Leroy Sane","Angelo Stiller","Felix Nmecha","Kai Havertz","Denis Undav","Nick Woltemeade"],
  "Curazao": ["Eloy Room","Trevor Doornbusch","Tyrick Bodak","Jurien Gaari","Roshon van Eijma","Sherel Floranus","Joshua Brenet","Shurandy Sambo","Armando Obispo","Riechedly Bazoer","Deveron Fonville","Leandro Bacuna","Juninho Bacuna","Godfried Roemeratoe","Kevin Felida","Livano Comenencia","Ar'jany Martha","Tyrese Noslin","Kenji Gorre","Brandley Kuwas","Gervane Kastaneer","Jeremy Antonisse","Jearl Margaritha","Jurgen Locadia","Sontje Hansen","Tahith Chong"],
  "Costa de Marfil": ["Yahia Fofana","Alban Lafont","Mohamed Kone","Ghislain Konan","Odilon Kossounou","Wilfried Singo","Evan Ndicka","Emmanuel Agbadou","Guela Doue","Ousmane Diomande","Clement Akpa","Franck Kessie","Jean Michael Seri","Ibrahim Sangare","Seko Fofana","Christ Inao Oulai","Parfait Guiagon","Nicolas Pepe","Oumar Diakite","Simon Adingra","Evann Guessand","Amad Diallo","Yan Diomande","Bazoumana Toure","Elye Wahi","Ange Yoan-Bonny"],
  "Ecuador": ["Hernan Galindez","Moises Ramirez","Gonzalo Valle","Felix Torres","Piero Hincapie","Joel Ordonez","Willian Pacho","Pervis Estupinan","Angelo Preciado","Jackson Porozo","Jordy Alcivar","Denil Castillo","John Yeboah","Kendry Paez","Alan Minda","Pedro Vite","Gonzalo Plata","Alan Franco","Moises Caicedo","Yaimar Medina","Kevin Rodriguez","Enner Valencia","Anthony Valencia","Jordy Caicedo","Nilson Angulo","Jeremy Arevalo"],
  // GRUPO F
  "Países Bajos": ["Mark Flekken","Robin Roefs","Bart Verbruggen","Nathan Ake","Denzel Dumfries","Jorrel Hato","Jurrien Timber","Jan Paul van Hecke","Virgil van Dijk","Micky van de Ven","Mats Wieffer","Ryan Gravenberch","Frenkie de Jong","Teun Koopmeijners","Tijjani Reijnders","Maarten de Roon","Guus Til","Quinten Timber","Brian Brobbey","Memphis Depay","Cody Gakpo","Justin Kluivert","Noa Lang","Donyell Malen","Crysencio Summerville","Wout Weghorst"],
  "Japón": ["Zion Suzuki","Keisuke Osako","Tomoki Hayakawa","Yuto Nagatomo","Takehiro Tomiyasu","Ko Itakura","Shogo Taniguchi","Hiroko Ito","Yukinari Sugawara","Ayumu Seko","Tsuyoshi Watanabe","Junnosuke Suzuki","Wataru Endo","Junya Ito","Ritsu Doan","Daichi Kamada","Takefusa Kubo","Ao Tanaka","Keito Nakamura","Kaishu Sano","Ayase Ueda","Daizen Maeda","Koki Ogawa","Yuito Suzuki","Keisuke Goto","Kento Shiogai"],
  "Túnez": ["Aymen Dahmen","Sabri Ben Hessen","Mouhib Chamakh","Montassar Talbi","Dylan Bronn","Ali Abdi","Yan Valery","Mohamed Amine Ben Hamida","Moutaz Neffati","Omar Rekik","Adem Arous","Raed Chikhaoui","Ellyes Shkiri","Hannibal Mejbri","Anis Ben Slimane","Mortadha Ben Ouanes","Ismael Gharbi","Hadj Mahmoud","Rani Khedira","Elias Achouri","Firas Chaouat","Hazem Mastouri","Elias Saad","Sebastian Tounekti","Khalil Ayari","Rayan Elloumi"],
  "Suecia": ["Kristoffer Nordfeldt","Viktor Johansson","Jacob Widell Zetterstrom","Victor Lindelof","Isak Hien","Gabriel Gudmundsson","Carl Starfelt","Emil Holm","Hjalmar Ekdal","Daniel Svensson","Gustaf Lagerbielke","Eric Smith","Elliot Stroud","Mattias Svanberg","Jesper Karlstrom","Yasin Ayari","Lucas Bergvall","Besfort Zeneli","Alexander Isak","Viktor Gyokeres","Ken Sema","Anthony Elanga","Benjamin Nygren","Alexander Bernhardsson","Gustaf Nilsson","Taha Ali"],
  // GRUPO G
  "Bélgica": ["Thibaut Courtois","Senne Lammens","Mike Penders","Thomas Meunier","Timothy Castagne","Arthur Theate","Zeno Debast","Maxim De Cuyper","Brandon Mechele","Koni De Winter","Joaquin Seys","Nathan Ngoy","Axel Witsel","Kevin De Bruyne","Youri Tielemans","Hans Vanaken","Amadou Onana","Nicolas Raskin","Romelu Lukaku","Leandro Trossard","Jeremy Doku","Dodi Lukebakio","Charles De Ketelaere","Alexis Saelemakers","Diego Moreira","Matias Fernandez-Pardo"],
  "Egipto": ["Mohamed El Shenawy","Mostafa Shobeir","Mohamed Alaa","El Mahdy Soliman","Hamdy Fathy","Ramy Rabia","Mohamed Hany","Ahmed Fatouh","Mohamed Abdelmonem","Yasser Ibrahim","Hossam Abdelmaguid","Karim Hafez","Tarek Alaa","Marwan Attia","Emam Ashour","Mohanad Lasheen","Mahmoud Saber","Nabil Emad","Mostafa Ziko","Mohamed Salah","Trezeguet","Zizo","Omar Marmoush","Ibrahim Adel","Haissem Hassan","Hamza Abdelkarim"],
  "Irán": ["Alireza Beiranvand","Payam Niazmand","Mahdi Torabi","Sadegh Moharrami","Majid Hosseini","Mohammad Kanaanizadegan","Milad Mohammadi","Shoja Khalilzadeh","Roozbeh Cheshmi","Ali Karimi","Saeid Ezatolahi","Ahmad Noorollahi","Alireza Jahanbakhsh","Mehdi Torabi","Omid Noorafkan","Ali Gholizadeh","Sardar Azmoun","Mehdi Ghayedi","Karim Ansarifard","Mehdi Taremi","Allahyar Sayyadmanesh","Saman Ghoddos","Ali Shojaei","Mohammad Mohebi","Morteza Pouraliganji","Ehsan Hajsafi"],
  "Nueva Zelanda": ["Max Crocombe","Alex Paulsen","Michael Woud","Tim Payne","Francis de Vries","Tyler Bindon","Michael Boxall","Liberato Cacace","Nando Pijnaker","Finn Surman","Callan Elliot","Tommy Smith","Joe Bell","Matthew Garbett","Marko Stamenic","Sarpreet Singh","Elijah Just","Alex Rufer","Ben Old","Callum McCowatt","Ryan Thomas","Lachlan Bayliss","Chris Wood","Kosta Barbarouses","Ben Waine","Jesse Randall"],
  // GRUPO H
  "España": ["Unai Simon","David Raya","Joan Garcia","Aymeric Laporte","Marc Cucurella","Marcos Llorente","Eric Garcia","Pedro Porro","Alex Grimaldo","Pau Cubarsi","Marc Cubill","Rodri","Fabian Ruiz","Mikel Merino","Pedri","Gavi","Martin Zubimendi","Alex Baena","Ferran Torres","Mikel Oyarzabal","Dani Olmo","Nico Williams","Lamine Yamal","Yeremy Pino","Borja Iglesias","Victor Munoz"],
  "Cabo Verde": ["Vozinho","Marcio Rosa","CJ dos Santos","Stopira","Roberto Lopes","Joao Paulo","Diney","Logan Costa","Steven Moreira","Wagner Pina","Sidny Lopes Cabral","Kelvin Pires","Jamiro Monteiro","Kevin Pina","Deroy Duarte","Telmo Arcanjo","Laros Duarte","Yannick Semedo","Ryan Mendes","Garry Rodrigues","Willy Semedo","Jovane Cabral","Gilson Benchimol","Dailon Livramento","Helio Varela","Nuno da Costa"],
  "Arabia Saudita": ["Mohammed Al-Owais","Nawaf Al-Aqidi","Ahmed Al-Kassar","Saud Abdulhamid","Hassan Al-Tambakti","Abdulelah Al-Amri","Nawaf Boushal","Ali Lajami","Ali Majrashi","Hassan Kadesh","Moteb Al-Harbi","Jehad Thakri","Mohammed Abu Al-Shamat","Salem Al-Dawsari","Abdullah Al-Khaibari","Mohamed Kanno","Nasser Al-Dawsari","Musab Al-Juwayr","Ayman Yahya","Ziyad Al-Johani","Sultan Mandesh","Alaa Al-Hejji","Firas Al-Buraikan","Saleh Al-Shehri","Abdullah Al-Hamdan","Khalid Al-Ghannam"],
  "Uruguay": ["Fernando Muslera","Sergio Rochet","Santiago Mele","Jose Maria Gimenez","Matias Vina","Mathias Olivera","Guillermo Varela","Ronald Araujo","Sebastian Caceres","Joaquin Piquerez","Santiago Bueno","Rodrigo Bentancur","Federico Valverde","Giorgian de Arrascaeta","Facundo Pellistri","Manuel Ugarte","Nicolas de la Cruz","Brian Rodriguez","Maximiliano Araujo","Agustin Canobbio","Emiliano Martinez","Rodrigo Zalazar","Juan Manuel Sanabria","Darwin Nunez","Federico Vinas","Rodrigo Aguirre"],
  // GRUPO I
  "Francia": ["Mike Maignan","Brice Samba","Robin Risser","Lucas Digne","Jules Kounde","Theo Hernandez","Lucas Hernandez","Dayot Upamecano","William Saliba","Ibrahima Konate","Malo Gusto","Maxence Lacroix","N'Golo Kante","Adrien Rabiot","Aurelien Tchouameni","Manu Kone","Warren Zaire-Emery","Kylian Mbappe","Ousmane Dembele","Marcus Thuram","Bradley Barcola","Michael Olise","Maghnes Akliouche","Desire Doue","Rayan Cherki","Jean-Philippe Mateta"],
  "Senegal": ["Edouard Mendy","Mory Diaw","Yehvann Diouf","Kalidou Koulibaly","Krepin Diatta","Moussa Niakhate","Ismail Jakobs","Abdoulaye Seck","El Hadj Malick Diouf","Antoine Mendy","Mamadou Sarr","Ilay Camara","Moustapha Mbow","Idrissa Gueye","Pape Gueye","Pape Matar Sarr","Pathe Siss","Lamine Camara","Habib Diarra","Bara Sapoko Ndiaye","Sadio Mane","Ismaila Sarr","Iliman Ndiaye","Nicolas Jackson","Bamba Dieng","Assane Diao"],
  "Noruega": ["Orjan Nyland","Egil Selvik","Sander Tangvik","Kristoffer Ajer","Julian Ryerson","Leo Ostigard","Marcus Holmgren Pedersen","David Moller Wolfe","Fredrik Andre Bjorkan","Torbjorn Heggem","Sondre Langas","Henrik Falchener","Martin Odegaard","Sander Berge","Patrick Berg","Kristian Thorstvedt","Morten Thorsby","Antonio Nusa","Fredrik Aursnes","Oscar Bobb","Jens Petter Hauge","Andreas Schjelderup","Thelo Aasgaard","Erling Haaland","Alexander Sorloth","Jorgen Strand Larsen"],
  "Iraq": ["Jalal Hassan","Fahad Talib","Bashar Resan","Ali Adnan","Rebin Sulaka","Amjed Attwan","Saad Natiq","Mohanad Abd","Hussein Ali","Ahmed Ibrahim","Basim Abbas","Ossama Rashid","Aymen Hussein","Emad Mohamed","Ali Jasim","Mohanad Lateef","Mazin Mohamed","Saif Ghadhban","Karrar Mohammed","Amir Al-Ammari","Mohammed Dawood","Mustafa Nadhim","Humam Tariq","Alaa Abbas","Mahdi Kamil","Ibrahim Bayesh"],
  // GRUPO J
  "Argentina": ["Emiliano Martinez","Geronimo Rulli","Juan Musso","Nicolas Otamendi","Nicolas Tagliafico","Nahuel Molina","Cristian Romero","Gonzalo Montiel","Lisandro Martinez","Leonardo Balerdi","Facundo Medina","Rodrigo De Paul","Leandro Paredes","Giovani Lo Celso","Alexis Mac Allister","Enzo Fernandez","Exequiel Palacios","Valentin Barco","Lionel Messi","Julian Alvarez","Lautaro Martinez","Nicolas Gonzalez","Thiago Almada","Giuliano Simeone","Nico Paz","Jose Manuel Lopez"],
  "Algeria": ["Luca Zidane","Oussama Benbot","Melvin Mastil","Aissa Mandi","Ramy Bensebaini","Mohamed Amine Tougai","Rayan Ait-Nouri","Jaouen Hadjam","Rafik Belghali","Zineddine Belaid","Achref Abada","Samir Chergui","Nabil Bentaleb","Ramiz Zerrouki","Hicham Boudaoui","Fares Chaibi","Houssem Aouar","Ibrahim Maza","Yacine Titraoui","Riyad Mahrez","Mohamed Amoura","Amine Gouiri","Anis Hadj Moussa","Adil Boulbina","Nadhir Benbouali","Fares Ghedjemis"],
  "Austria": ["Alexander Schlager","Florian Wiegele","Patrick Pentz","David Affengruber","Kevin Danso","Stefan Posch","David Alaba","Philipp Lienhart","Phillipp Mwene","Alexander Prass","Marco Friedl","Michael Svoboda","Xaver Schlager","Nicolas Seiwald","Marcel Sabitzer","Florian Grillitsch","Carney Chukwuemeka","Romano Schmid","Christoph Baumgartner","Konrad Laimer","Patrick Wimmer","Paul Wanner","Alessandro Schopf","Marko Arnautovic","Michael Gregoritsch","Sasa Kalajdzic"],
  "Jordania": ["Yazeed Abulaila","Mohammad Abu Hashem","Feras Shelbaieh","Baha Faisal","Mohammad Al-Dardour","Yazan Al-Naimat","Oday Dabbagh","Musa Al-Taamari","Mousa Suleiman","Ahmad Al-Sarraf","Khaled Al-Shawabkeh","Ahmad Saleh","Abdullah Nasib","Abdallah Nasib","Mohammad Rasheed","Abdullah Al-Zoubi","Yasser Al-Waked","Salem Al-Ajalin","Hussam Abu Ali","Ahmad Ibrahim","Mujahid Al-Qudah","Anas Bani Yaseen","Omar Khrisat","Khairy Kaied","Ibrahim Sfran","Malik Kafafi"],
  // GRUPO K
  "Portugal": ["Diogo Costa","Jose Sa","Rui Silva","Joao Cancelo","Diogo Dalot","Ruben Dias","Goncalo Inaco","Nuno Mendes","Renato Veiga","Matheus Nunes","Nelson Semedo","Tomas Araujo","Bruno Fernandes","Joao Neves","Bernardo Silva","Vitinha","Ruben Neves","Samu Costa","Cristiano Ronaldo","Rafael Leao","Pedro Neto","Francisco Conceicao","Joao Felix","Goncalo Guedes","Goncalo Ramos","Francisco Trincao"],
  "Uzbekistán": ["Eldor Shomurodov","Jasur Yakhshiboev","Jamshid Iskanderov","Otabek Shukurov","Dostonbek Khamdamov","Musayev Nodir","Sherzod Nishonov","Oybek Sobirov","Firdavs Odiljonov","Abbosbek Fayzullaev","Jakhongir Sidiqov","Sanjar Tursunov","Bekhruz Mirzaev","Umid Hamrobekov","Khusan Khamraliev","Otabek Abutov","Bobur Mirzaev","Islom Nazarov","Shamsiddin Shokirov","Mirzohid Giyosov","Sardor Rashidov","Husayn Norchaev","Lochinbek Iskandarov","Anvar Hasanov","Jasurbek Yakhshiboev","Muzaffar Mirzaev"],
  "Colombia": ["David Ospina","Camilo Vargas","Alvaro Montero","Davinson Sanchez","Santiago Arias","Yerry Mina","Daniel Munoz","Johan Mojica","Jhon Lucumi","Deiver Machado","Willer Ditta","James Rodrigues","Jefferson Lerma","Juan Fernando Quintero","Jhon Arias","Richard Rios","Kevin Castano","Jorge Carrastal","Jaminton Campaz","Juan Portilla","Gustavo Puerta","Luis Diaz","Jhon Cordoba","Luis Suarez","Cucho Hernandez","Andres Gomez"],
  "DR Congo": ["Lionel Mpasi","Timothy Fayulu","Matthieu Epolo","Chancel Mbemba","Arthur Masuaku","Gedeon Kalulu","Joris Kayembe","Dylan Batubinsika","Axel Tuanzebe","Aaron Wan-Bissaka","Rocky Bushiri","Steve Kapuadi","Meschak Elia","Samuel Moutoussamy","Edo Kayembe","Charles Pickel","Gael Kakuta","Noah Sadiki","Nathanael Mbuku","Ngal'ayel Mukau","Brian Cipenga","Cedric Bakambu","Theo Bongonba","Fiston Mayele","Yoane Wissa","Simon Banza"],
  // GRUPO L
  "Inglaterra": ["Jordan Pickford","Dean Henderson","Aaron Ramsdale","Trent Alexander-Arnold","Kyle Walker","John Stones","Harry Maguire","Marc Guehi","Ezri Konsa","Luke Shaw","Kieran Trippier","Ben White","Declan Rice","Jude Bellingham","Phil Foden","Kobbie Mainoo","Adam Wharton","Conor Gallagher","Morgan Gibbs-White","Bukayo Saka","Harry Kane","Marcus Rashford","Ollie Watkins","Jarrod Bowen","Anthony Gordon","Eberechi Eze"],
  "Croacia": ["Dominik Livakovic","Ivica Ivusic","Nediljko Labrovic","Josip Juranovic","Josip Stanisic","Domagoj Vida","Martin Erlic","Josko Gvardiol","Borna Barisic","Borna Sosa","Duje Caleta-Car","Lovro Majer","Mateo Kovacic","Mario Pasalic","Luka Modric","Marcelo Brozovic","Nikola Vlasic","Martin Baturina","Ivan Perisic","Ante Budimir","Andrej Kramaric","Ivan Zizic","Bruno Petkovic","Marko Pjaca","Mislav Orsic","Dario Spikic"],
  "Ghana": ["Joseph Wollacott","Lawrence Ati-Zigi","Ibrahim Danlad","Andrew Yiadom","Tariq Lamptey","Alexander Djiku","Gideon Mensah","Baba Rahman","Jonathan Mensah","Daniel Amartey","Abdul Mumin","Thomas Partey","Daniel Kofi Kyereh","Mohammed Kudus","Iddrisu Baba","Abdul Salis Samed","Elisha Owusu","Antoine Semenyo","Jordan Ayew","Andre Ayew","Ransford Yeboah","Osman Bukari","Abdul Fatawu","Ibrahim Sulemana","Inaki Williams","Kamaldeen Sulemana"],
  "Panamá": ["Luis Mejia","Orlando Mosquera","Roderick Miller","Fidel Escobar","Eric Davis","Cesar Blackman","Andres Andrade","Harold Cummings","Roderick Miller","Anibal Godoy","Alberto Quintero","Adalberto Carrasquilla","Cristian Martinez","Rolando Blackburn","Gabriel Torres","Ismael Diaz","Cecilio Waterman","Freddy Gondola","Riquelme Caballero","Jose Fajardo","Edgardo Fariña","Abdiel Ayarza","Alexis Castillo","Jovanny Gouverne","Cesar Yanis","Ernesto Walker"],
}
